on:
    pull_request:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'infrastructure/specs/amase.anod'
            - 'infrastructure/install-libexec/**'
            - 'anod'
    push:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'infrastructure/specs/amase.anod'
            - 'infrastructure/install-libexec/**'
            - 'anod'
    schedule:
        - cron: '45 3 * * 4'
    workflow_dispatch:

name: Build OpenAMASE
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                env: [
                    {os: ubuntu-20.04, python: '3.8'},
                    {os: ubuntu-22.04, python: '3.10'}
                ]
                component: [amase]
                qualifier: [scenario=release]
        runs-on: ${{ matrix.env.os }}
        steps:
            - uses: actions/checkout@v4
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.env.python }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.env.python }}

            - name: Set up java
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Install infrastructure
              run: |
                  cd OpenUxAS
                  infrastructure/install -vv --no-gnat --no-java -y

            - name: Build OpenAMASE
              run: |
                  cd OpenUxAS
                  ./anod -v build ${{ matrix.component }} --qualifier=${{ matrix.qualifier}}
