on:
    push:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'infrastructure/specs/**'
            - 'infrastructure/install-libexec/**'
            - 'resources/run-lmcpgen'
            - 'resources/run_lmcpgen.py'
    pull_request:
        paths:
            - 'infrastructure/uxas/**'
            - 'infrastructure/paths.sh'
            - 'infrastructure/specs/**'
            - 'infrastructure/install-libexec/**'
            - 'resources/run-lmcpgen'
            - 'resources/run_lmcpgen.py'
    workflow_dispatch:
    schedule:
        - cron: '20 3 * * 4'

name: Test Running LmcpGen
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                env: [
                    {os: ubuntu-22.04, python: '3.10'},
                    {os: ubuntu-24.04, python: '3.12'}
                ]
        runs-on: ${{ matrix.env.os }}
        steps:
            - uses: actions/checkout@v4
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.env.python }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.env.python }}

            - name: Set up java
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Install infrastructure
              run: |
                  cd OpenUxAS
                  infrastructure/install -vv --no-gnat --no-java -y

            - name: LMCP and Amase devel setup
              run: |
                  cd OpenUxAS
                  ./anod devel-setup lmcp
                  ./anod devel-setup amase

            - name: Run LmcpGen
              run: |
                  cd OpenUxAS
                  resources/run-lmcpgen
