on:
    push:
        paths:
            - 'infrastructure/uxas/**'
    pull_request:
        paths:
            - 'infrastructure/uxas/**'
    workflow_dispatch:
    schedule:
        - cron: '10 3 * * 4'

name: Check uxas Build-Automation Module
jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                env: [
                    {os: ubuntu-22.04, python: '3.10'},
                    {os: ubuntu-24.04, python: '3.12'}
                ]
        runs-on: ${{ matrix.env.os }}
        steps:
            - uses: actions/checkout@v4
              with:
                  path: OpenUxAS

            - name: Set up python ${{ matrix.env.python }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.env.python }}

            - name: Set up testing tools
              run: |
                  pip install --upgrade pip
                  pip install tox
                  python3 -m pip install types-PyYAML

            - name: Run testsuite and style checks
              run: |
                  cd OpenUxAS/infrastructure/uxas
                  tox
